package com.caizhixing.poetry.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.caizhixing.poetrywidget.Poetery;

import com.caizhixing.poetry.db.PoeteryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig poeteryDaoConfig;

    private final PoeteryDao poeteryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        poeteryDaoConfig = daoConfigMap.get(PoeteryDao.class).clone();
        poeteryDaoConfig.initIdentityScope(type);

        poeteryDao = new PoeteryDao(poeteryDaoConfig, this);

        registerDao(Poetery.class, poeteryDao);
    }
    
    public void clear() {
        poeteryDaoConfig.clearIdentityScope();
    }

    public PoeteryDao getPoeteryDao() {
        return poeteryDao;
    }

}
